version: '3'
##################################
services:
  #################
  ovsdb-server:
    hostname: ovs-server
    container_name: ovsdb-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_NICE
    networks:
      ovscomm:
        ipv4_address: 172.18.0.2
    volumes:
      - /lib/modules:/lib/modules
      - /home/core/ovs/log:/var/log/openvswitch
      - /home/core/ovs/var/lib/openvswitch:/var/lib/openvswitch
      - /home/core/ovs/var/run/openvswitch:/var/run/openvswitch
      - /home/core/ovs/etc/openvswitch:/etc/openvswitch
    security_opt:
      - label=disable
    privileged: true
    image: openvswitch/ovs:latest
    command: ovsdb-server
  #################
  switch:
    hostname: s1
    container_name: s1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_NICE
    networks:
      ovscomm:
        ipv4_address: 172.18.0.3
    volumes_from:
      - ovsdb-server
    security_opt:
      - label=disable
    privileged: true
    image: openvswitch/ovs:latest
    command: ovs-vswitchd
  #################
  u1:
    hostname: h1
    container_name: h1
    image: host:latest
    command: tail -F anything
    network_mode: none
#    depends_on:
#      - ovs-vswitchd
  #################
  u2:
    hostname: h2
    container_name: h2
    image: host:latest
    command: tail -F anything
    network_mode: none
#    depends_on:
#      - ovs-vswitchd
  #################
  u3:
    hostname: h3
    container_name: h3
    image: host:latest
    command: tail -F anything
    network_mode: none
#    depends_on:
#      - ovs-vswitchd
  #################
  ryu:
    hostname: ryu
    container_name: ryu
    image: osrg/ryu:latest
    networks:
      ovscomm:
        ipv4_address: 172.18.0.4
    #network_mode: "service:ovs-vswitchd"
    #tty: true
    #stdin_open: true
    #privileged: true
    cap_add:
      - NET_ADMIN
    #command: /bin/bash
    command: bash -c "apt-get update && apt-get install -y net-tools && tail -f /dev/null"
##################################
networks:
  ovscomm:
#  n1:
#  network2:
